### ISSUE TITLE
Get result or disable first validate_token call

### ISSUE THREAD

**Issue by gustavogsimas** [neroniaky/angular-token#134]
Hello,

I have a doubt, I know that we are in alpha, but do or will we have a way to get the result or disable the first validate_token call that is made to the back end?

In the [ng-token-auth gem](https://github.com/lynndylanhurley/ng-token-auth#authvalidation-success) that I'm currently using in some of my angular 1 projects, it has a $scope.$on to get the result. I don't know if in angular 2 we have something related or close to it.

Besides the first automatic call, currently I'm making one more validate_token call. Thanks you for your answers =)

**Comment by neroniaky** [comment]
Hey @twizzzlers, the validateToken call is made to fill `.currentUserData()`, which includes things like the users email address. 
Usually you don't have to make an additional call. Could you give me an example what you're using it for? Thanks!

**Comment by twizzzlers** [comment]
For example, I wanna see if the user is logged as soon as the user enters the page. I tried with the`.currentUserData()`, but it is undefined until the validate_token call is answered. That's why I questioned:

Can I get the result of this first validate_token call? Or how can I call the `.currentUserData()` after the validate_token call is made? Thanks.

**Comment by neroniaky** [comment]
Thanks for your example. The first `validate_token()` get run inside the `init()`, which doesn't return an Observable (yet?). I'm not sure how to best handle this case yet, so I guess you have to call `.validate_token` twice until this is implemented, or create a PR :wink:.

**Comment by neroniaky** [comment]
7.1.0-rc.0 exposes userData as BehaviorSubject. So you can now subscribe to userData, which should solve your problem. Please reopen if it doesn't.

**Comment by TimSwerts** [comment]
I want to reopen this issue. I have kind of the **_same problem as in the issue #253._** I tried to reload the `.currentUserData` twice and it's not working for me. I think it has something to do with the way I am confronted with this problem.

I am making a AuthGuard or let's say I made it and it works all the time when I am logged in an when I am browsing trough my application. Now I was testing the basic security of my application and I found out that when I use the `.currentUserData` in my logic of canActivate in my guard and then type in a guarded link, the `.currentUserData` will be empty so my guard isn't functioning.

I've tried to validate the Token but that doesn't work iether. I think the problem is when I force the browser to go to a certain page the authGaurd works before the component gets loaded in that way the `.currentUserData` will not be available.

If there is any solution for this problem or if you have extra questions, feel free to respond.
