### ISSUE TITLE
signIn - wrong headers

### ISSUE THREAD

**Issue by krystian50** [neroniaky/angular-token#465]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior

Currently sign_in request set up wrong header:
`Accept: application/json, text/plain, */*`

As the result API returns 422 HTTP code and can't process this data.

## Expected behavior

it should be: 
`Accept: application/json, text/plain`

## What is the motivation / use case for changing the behavior?

Currently I can't use the library, because there's no globalConf or any interceptor to manually set up headers for sign in endpoint.
## Environment

Angular-Token version: 6.0.1
Angular version: 6.1.3

Bundler
- [x] Angular CLI (Webpack)
- [ ] Webpack
- [ ] SystemJS

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by arjenbrandenburgh** [comment]
As far as I'm aware, we don't set the 'Accept'-header in this library. Since we're using HTTP Interceptors where we simply add headers, it seems the header you're referring to either comes from somewhere in your own code or is default.

In version 0.2.0 we used to have the option to set default headers for these requests, but we needed that since the library was a wrapper around the HttpModule. In the current implementation, that's no longer the case and thus have removed this option.

In my own implementations, my API has no problems with these headers though (Ruby5 API, devise, Angular6). I suggest you use an HttpInterceptor to change the default Accept headers you send out in your requests if you feel that would solve your problem.

**Comment by arjenbrandenburgh** [comment]
Closing this issue. If you still feel this is a bug or shortcoming, feel free to re-open.
