### ISSUE TITLE
Migration Angular 7

### ISSUE THREAD

**Issue by penMANship** [neroniaky/angular-token#487]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ x] Other... Please describe: My environment is Rails 5 running on localhost:3000 and Angular(5 or 7) running on localhost:4200.  The client requests are now all xmlhttp requests not http requests as they were in Angular2-token and they cannot get past CORS.  This appears to be a rxjs 5 vs. 6 issue.  I have posted the question on Stack Overflow but have gotten no answers.  Do you have any instruction.

I am continuing my development using Angular2-token until I can get a resolution on this.  

Thanks for any help.
Paul NIelsen
paul@thelanding.us

## Environment

Angular-Token version: X.Y.Z
Angular version: X.Y.Z

Bundler
- [x ] Angular CLI (Webpack)
- [ ] Webpack
- [ ] SystemJS

Browser:
- [ x] Chrome (desktop) version 72.0.3626.81
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by neroniaky** [comment]
Hi @penMANship, thank you for this issue. I think I was able to reproduce the error you are describing.
HttpClient is sending XMLHttpRequest's which it should and it is totally fine. The CORS error I got was because of an invalid auth header.

Please try the following:
- Check your browsers developer tools and look what the header `access-token` transmits. I my case it was `fake-access-token`.
- Retry your application with in your browser incognito mode.

The problem is that the example app sets an `access-token` for the url `localhost` which is always newer than a token from a real application, so it never gets updated. Def need to fix this.

**Comment by neroniaky** [comment]
Closed because of inactivity. Please reopen if necessary.
